### ISSUE TITLE
Administrative Items for move

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/go-digest#17]
Now that this repository has been moved to opencontainers, we'll need to update several administrative items. If there is anything missing, please edit this description or comment and I'll add it here. Once an item has a PR open, we can add it here and check it off when merged.

- [X] Update travis CI build configuration (nothing to do here)
- [x] Update project urls (#22)
- [x] MAINTAINERS
  - [x] Update maintainers with OCI project format (#19)
  - [x] Setup maintainers group (#15)
  - [x] PullApprove configuration (#16)
- [x] Update files to have license header, per image-spec/runtime-spec (#28)
- [x] ~~Apply oci project template (#20)~~
- [x] Update security statement to be in line with OCI procedures (#27)

**Comment by caniszczyk** [comment]
Great to see this done, thanks @stevvooe
